version: '3'

services:
  # Hadoop NameNode
  namenode:
    image: biggis/hdfs:2.7.1
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - NAMENODE_HOSTNAME=namenode
    volumes:
      - /home/user/hadoopdata:/hadoop/dfs/name
    networks:
      - hadoop_network
    ports:
      - "50070:50070"  # Web UI

  # Hadoop DataNode
  datanode:
    image: biggis/hdfs:2.7.1
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - NAMENODE_URI=hdfs://namenode:8020
    volumes:
      - /home/user/hadoopdata:/hadoop/dfs/data
    networks:
      - hadoop_network

  # Hive Metastore
  hive-metastore:
    image: bde2020/hive:2.3.0
    container_name: hive-metastore
    environment:
      - METASTORE_DB_HOST=hive-metastore-db
      - METASTORE_DB_PORT=3306
    volumes:
      - /home/user/hivedata:/hive/metastore_data
    networks:
      - hadoop_network
    depends_on:
      - hive-metastore-db

  # HiveServer2
  hive-server2:
    image: bde2020/hive:2.3.0
    container_name: hive-server2
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "10000:10000"  # HiveServer2 port
    networks:
      - hadoop_network
    depends_on:
      - hive-metastore

  # MySQL for Hive Metastore
  hive-metastore-db:
    image: mysql:5.7
    container_name: hive-metastore-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=hive
    networks:
      - hadoop_network
    volumes:
      - /home/user/hivedata/mysql:/var/lib/mysql
    ports:
      - "3306:3306"  # MySQL port

networks:
  hadoop_network:
    driver: bridge
